Add the ability to add app shortcuts to open chuck
jgilfelt/chuck pull request #49
Opened 2017-05-25 22:07 UTC by degill

This commit adds the ability to add an app shortcut to the clients' launcher icon on android devices running android 7.0 and above. With that app shortcut the Chuck UI can be accessed. This can be useful if no notification is desired but there still need to be a simple way to enter chuck.

2018-09-19 22:19 UTC, olivierperez requested changes
You should maybe add a method to remove the shortcut too.

2018-09-19 22:19 UTC, olivierperez commented on library/src/main/java/com/readystatesoftware/chuck/Chuck.java
> +                .setLongLabel("Open Chuck UI")
The label should be retrieved from the resources, or maybe given by paramters to let de developer choose the wording.

2018-09-19 22:19 UTC, olivierperez commented on library/src/main/java/com/readystatesoftware/chuck/Chuck.java
> +    @SuppressWarnings("WeakerAccess")
I'm not fan of this SuppressWarnings

2018-10-26 07:44 UTC, degill commented on library/src/main/java/com/readystatesoftware/chuck/Chuck.java
> +    @SuppressWarnings("WeakerAccess")
This function is obviously not called from within the library, thus there will be a warning that its access can be weaker, but apps need access to it so it must be public -> Get rid of the warning.

2026-04-21 04:45 UTC, closed without merging